package com.mycompany.interfaz;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Usuario extends javax.swing.JFrame {
    
    Connection con=null;
    Statement stmt=null;
    String var,var2;
    
    

    /**
     * Creates new form NewJFrame
     */
    public Usuario() {
        
        
        
        initComponents();
        this.setTitle("Registro de Usuario");
        ImageIcon icono = new ImageIcon("C:\\Users\\USER\\Desktop\\imagenes\\logoEdited.jpg");
        this.setIconImage(icono.getImage());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Nick:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel8.setText("Tipo de Usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel2.setText("id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, -1));

        jButton2.setLabel("Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jButton3.setLabel("cons user");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jButton4.setLabel("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\imagenes\\background2Edited.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void consulta() {
        String cap="";
        ResultSet rs = null;
        var2 = var;
        String sql2="Select id, nombre, domicilio, telefono, nick, contraseña, tipousuario FROM usuarios where nombre = '"+var2+"'";
            
   try { 
       
                  String url = "jdbc:mysql://localhost:3306/interfaz"; 
                  String usuario = "root"; 
                  String contraseña = "2812";
                  
     Class.forName("com.mysql.jdbc.Driver").newInstance(); 
     
     
     con = DriverManager.getConnection(url,usuario,contraseña); 

     if ( con != null ) 
	   System.out.println("Se ha establecido una conexión a la base de datos " + 
	                                       "\n " + url ); 
	  
	stmt = con.createStatement(); 
	rs = stmt.executeQuery(sql2); 
        
	int i=1; 
	   while ( rs.next() ) { 
               
	           String id = rs.getString("id"); 
	           String inom = rs.getString("nombre"); 
	           String idom = rs.getString("domicilio"); 
                   String itel = rs.getString("telefono"); 
                   String inick = rs.getString("nick"); 
                   String ipass = rs.getString("contraseña");
                   String itipo = rs.getString("tipousuario");
	           System.out.println("Sitio Web "+ (i++) + ":\n" 
	                     
                           + id + "\n"
                           + inom + "\n" 
                           + idom + "\n" 
                           + itel + "\n"
	                   + inick + "\n"
                           + ipass + "\n"
                           + itipo + "\n\n" ); 
                   
                   jTextField5.setText(id);
                   jTextField1.setText(inom);
                   jTextField2.setText(idom);
                   jTextField3.setText(itel);
                   jTextField4.setText(inick);
                   jPasswordField1.setText(ipass);
                   jComboBox1.setSelectedItem(itipo);
                  
	         } 
	        } 
                  catch( SQLException ex ) { 
                      ex.printStackTrace(); 
	                  } catch (InstantiationException ex) { 
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
	  
	              finally { 
	                  if ( rs != null ) { 
	                      try    { 
	                          rs.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
	                      } 
	                  } 
	                  if ( stmt != null ) { 
	                      try    { 
	                          stmt.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
	                      } 
	                  } 
	                  if ( con != null ) { 
	                      try    { 
	                          con.close(); 
	                      } catch( SQLException ex ) { 
	                          System.out.println( ex.getMessage()); 
	                          ex.printStackTrace(); 
         } 
       }
     }    
    }//fin del metodo consulta
    
    public void actualizar() {
        
        String cadena1,cadena2,cadena3,cadena4,cadena5,cadena6,cadena7;
     
       cadena1 = jTextField5.getText();
       cadena2 = jTextField1.getText();
       cadena3 = jTextField2.getText();
       cadena4 = jTextField3.getText();
       cadena5 = jTextField4.getText();
       cadena6 = jPasswordField1.getText();
       cadena7 = jComboBox1.getSelectedItem().toString();
     
    
     if (jTextField1.getText().equals("")) {
         
         javax.swing.JOptionPane.showMessageDialog(this,"1-. Consulte el nombre del cliente\n 2-. Actualice el dato deseado en el campo correspondiente","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
     }
     else {   
     
     try { 
                  String url = "jdbc:mysql://localhost:3306/tu_base_de_datos"; 
                  String usuario = "root"; 
                  String contraseña = "tu_contraseña"; 
                  
                  Class.forName("com.mysql.jdbc.Driver").newInstance(); 
                  con = DriverManager.getConnection(url,usuario,contraseña); 
                  if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("update ignore usuarios set id= '"+cadena1+"' , nombre = '"+cadena2+"',domicilio = '"+cadena3+"',telefono = '"+cadena4+"', nick = '"+cadena5+"', password = '"+cadena6+"', tipousuario = '"+cadena7+"' where id = '"+jTextField5.getText()+"' || nombre = '"+jTextField1.getText()+"' || domicilio = '"+jTextField2.getText()+"' || telefono = '"+jTextField3.getText()+"' || nick = '"+jTextField4.getText()+"' || password = '"+jPasswordField1.getText()+"' || tipousuario = '"+jComboBox1.getSelectedItem()+"'"); 

                  System.out.println("Los valores han sido Actualizados"); 
                  } 
                  catch( SQLException e ) { 
                      e.printStackTrace(); 
                  } catch (ClassNotFoundException ex) { 
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
  
              finally { 
                  if ( con != null ) { 
                      try    { 
                          con.close(); 
                          stmt.close(); 
                      } catch( Exception e ) { 
                          System.out.println( e.getMessage()); 
                      } 
                  } 
     }
     javax.swing.JOptionPane.showMessageDialog(this,"Actualizado correctamente!","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
     } 
        this.jTextField5.setText("");
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jPasswordField1.setText("");
    }


    
    //guardar registro
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //obteniendo los valores del formulario y almacenando en variables
        String cadena2,cadena3,cadena4,cadena5,cadena6,cadena7;
        cadena2 = jTextField1.getText();
        cadena3 = jTextField2.getText();
        cadena4 = jTextField3.getText();
        cadena5 = jTextField4.getText();
        cadena6 = jPasswordField1.getText().toString();
        cadena7 = jComboBox1.getSelectedItem().toString();
        
        //validadcion
        if(jTextField1.getText().equals("") || (jTextField2.getText().equals("")) || (jTextField3.getText().equals(""))
                || (jTextField4.getText().equals("")) || (jPasswordField1.getText().equals("")) 
                || (jComboBox1.getSelectedItem().equals(""))){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n","AVISO",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextField1.requestFocus();
        }
      else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/interfaz?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
            String usuario = "root";
            String contraseña = "2812";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance();
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt =  con.createStatement(); 
                  
                 
                  
                  stmt.executeUpdate("INSERT INTO usuarios VALUES('" + 0 + "','"+cadena2 +
                          "','"+cadena3+"','"+cadena4+"','"+cadena5+"','"+cadena6+"','"+cadena7+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                  
                 
                   
        } catch (InstantiationException ex) {
           Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
       }   /* catch (SQLException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jTextField1.setText("");
        this.jPasswordField1.setText("");  

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        //limitando a utilizar solo letras (revisar de valores de caracteres)
        char c = evt.getKeyChar();
        if((c < 'a' || 'z' < c) && (c < 'A' || c > 'Z') && (c < ' ' ||c>' '))evt.consume();
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
    
        //limitando a utilizar solo letras (revisar de valores de caracteres)
        char d = evt.getKeyChar();
        if(d < '0' || '9' <  d)evt.consume();
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        ConsultaUsuario cu = new ConsultaUsuario();
        cu.setLocationRelativeTo(null);
        cu.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    
    //consulta usuario
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String cap="";
        ResultSet rs = null; 
         var = javax.swing.JOptionPane.showInputDialog(this,"Nombre del usuario","Consulta usuario",javax.swing.JOptionPane.QUESTION_MESSAGE);
        String sql="SELECT* FROM  usuarios WHERE nombre = '"+var+"'";
        if(var == null)  
        javax.swing.JOptionPane.showMessageDialog(this,"La accion fue cancelada","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
      else {   
        if (var.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,"Favor de ingresar el nombre de usuario\nque desea consultar","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
         else {
        try {
            
            String url = "jdbc:mysql://localhost:3306/interfaz";
            String usuario = "root";
            String contraseña = "2812";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement(); 
                  rs = stmt.executeQuery(sql);
                        
          while(rs.next()) {
              
               cap = rs.getString("tipousuario"); 
                  
          if (cap.equals("Usuario") || cap.equals("Administrador") || cap.equals("manager") || cap.equals("servidor")) {
               
              consulta();     
             
          }
         }   // fin del bucle While
         
        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
//           Logger.getLogger(portada.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
              }
            }
           if (!cap.equals("Usuario") && !cap.equals("Administrador") && !cap.equals("manager") && !cap.equals("servidor")) {
                System.out.println(var);
              javax.swing.JOptionPane.showMessageDialog(this,"El usuario no fue encontrado\n","ERROR!", javax.swing.JOptionPane.ERROR_MESSAGE);
             
          }
        }
      }  

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        actualizar();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
